name: ML Model CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Ensure it matches your environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure all dependencies are listed here

    - name: Run pytest
      run: |
        pytest  # Runs all the tests in the default test directory (e.g., test/)

  deploy:
    needs: test  # Ensure deployment only occurs after tests pass
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t adult_income .

    - name: Run Docker container for FastAPI app
      run: |
        docker run -d -p 5000:5000 adult_income

    - name: Wait and test FastAPI
      run: |
        sleep 5
        curl http://localhost:5000/predict || echo "FastAPI not running"
